FROM python:3.10-slim

WORKDIR /app

COPY . /app
COPY certs/ /app/certs/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --timeout=300 --retries=10 -r requirements.txt
EXPOSE 5002

CMD ["python3", "core/ausf.py"]
