FROM python:3.10-slim

WORKDIR /app

RUN pip install --upgrade pip

RUN pip install \
    --default-timeout=1200 \
    --retries=10 \
    --no-cache-dir \
    flask \
    requests \
    prometheus_client \
    pandas \
    joblib \
    scikit-learn
