apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      containers:
      - name: nrf
        image: nrf:v1
        ports:
        - containerPort: 5001
volumeMounts:
  - name: nrf-tls
    mountPath: /app/certs

volumes:
  - name: nrf-tls
    secret:
      secretName: nrf-tls
