apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
      - name: smf
        image: smf-service:latest
        ports:
        - containerPort: 5003
